version: '3.8'
services: 
  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rishat
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  django:
    build: .
    environment:
      URL: 0.0.0.0:8000
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rishat
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY: <ваш secret key>
      PUBLISH_KEY: <ваш publish key>
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_project/:/django_test
    ports:
      - "8000:8000"
    depends_on:
      - db