# Generated by Django 3.2.6 on 2022-09-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rishat_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Вещь', 'verbose_name_plural': 'Вещи'},
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'RUB'), ('usd', 'USD')], default='rub', max_length=3, verbose_name='Валюта'),
        ),
    ]
